### ISSUE TITLE
Hola, problemas para instalar Caneda

### ISSUE THREAD

**Issue by victorchoke** [Caneda/Caneda#1]
Hola, estoy instalando desde un ubuntu 15.04 x86_64

Tuve el siguiente problema en el make
Could NOT find Qwt (missing: _QWT_VERSION_MATCH) (Required is at least
  version "6.1.2"

Logre instalar la librería que me indica, pero en una ruta que parece que mi sistema no lo reconoce /usr/local/qwt-6.1.2 en la explicación de instalación de la librería me indica que tengo que agregarles las rutas al programa en si mismo (no se si pasárselo como parámetro al cmake) o en que parte del programa incorporarlo.

Disculpa las molestias! Me interesa mucho probar el programa.

**Comment by parejaobregon** [comment]
Hola Victor,

Gracias por intentar usar Caneda y reportar los bugs que encuentres :)

La librería Qwt se usa actualmente en Caneda para graficar los resultados de las simulaciones. En un futuro, será reemplazada por QCharts, simplificando un poco las cosas.

Volviendo a tu problema, no debería hacer falta que modifiques nada del código fuente ya que se tienen en cuenta todas las posibles rutas de instalación Qwt. En particular, ese mensaje que te tira es un chequeo del archivo "caneda-sources/cmake/Modules/FindQwt.cmake". Me llama la atención que no te encuentre Qwt, ya que yo también uso Qwt instalado en esa misma ruta ("/usr/local/qwt-6.1.2/"). Seguramente es algún problema simple de resolver.

Te propongo lo siguiente:
- Fijate el contenido de la carpeta "/usr/local/qwt-6.1.2/". Debería ser algo así como "doc  features  include  lib". De ser así, estamos por el buen camino.
- Chequea que no tengas instalada otra versión de la librería. Si en algún momento instalaste otra versión anterior (directamente o como dependencia de algún otro programa), al ejecutar cmake se encontrará con esa otra versión primero. En ese caso, necesitarías desinstalar esa otra versión. El comando "aptitude search ~iqwt" te debería decir todas las versiones de qwt que tenés instaladas en tu máquina.

Adicionalmente del siguiente link parece que Ubuntu tiene las versiones más nuevas de qwt para instalar directamente de repositorio: https://launchpad.net/ubuntu/+source/qwt. Si es así, como alternativa, no necesitás compilar qwt sino que podrías utilizar directamente las versiones del repositorio. Si preferís proceder de esa manera, los paquetes que deberías instalar son libqwt-qt5-dev y libqwt-qt5-6 (acordate de borrar la carpeta qwt-6.1.2 que instalaste localmente) .

Espero no haberte mareado. Por favor, manteneme al tanto si podés solucionar el problema con el paso anterior y sino seguimos viendo cómo proceder.

**Comment by victorchoke** [comment]
Perfecto te digo la secuencia de pasos con la que resolví el problema, era justo como me indicaste:

1. Desinstale las versiones viejas de qwt
2. Borre el interior de la carpeta build
3. Volví a recompilar.

Ahora me surgió otro problema
[ 59%] Built target dialogs
Linking CXX executable caneda
/usr/bin/ld: /usr/local/qwt-6.1.2/lib/libqwt.so: referencia sin definir al símbolo '_ZN13QSvgGeneratorC1Ev'
/usr/lib/x86_64-linux-gnu/libQtSvg.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/caneda.dir/build.make:1044: recipe for target 'src/caneda' failed
make[2]: *** [src/caneda] Error 1
CMakeFiles/Makefile2:83: recipe for target 'src/CMakeFiles/caneda.dir/all' failed
make[1]: *** [src/CMakeFiles/caneda.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Como si me faltara agregar
QT += svg@
o como si el qwt no pudiera acceder a qwtsvg o tuviera una librería vieja

######################################################################
# If you want to display svg images on the plot canvas, or
# export a plot to a SVG document
######################################################################

QWT_CONFIG     += QwtSvg

Otra cosa que te quería consultar es que no me aparece la 6.1.2 instalada ni figura en synaptic ni por aptitud, aunque si el cmake compilando el Caneda me lo reconoce, no se si ese sera la fuente del problema.

Gracias por tu tiempo

**Comment by parejaobregon** [comment]
Muy bien, vamos avanzando.

En principio, la línea que mencionás ("QWT_CONFIG += QwtSvg") no haría falta ya que eso es para qmake y en Caneda se utiliza cmake (el cual utiliza una línea parecida que podés encontrar en el archivo CMakeLists.txt). Por otra parte, es natural que en synaptic, apt-get, aptitude, etc, no te aparezca Qwt ya que instalaste Qwt manualmente así que el manejador de paquetes nunca se enteró (las versiones del repositorio las desinstalaste todas). Finalmente, cmake sí encuentra Qwt ya que en los archivos de Caneda hay instrucciones para que busque en todos los lugares donde puede llegar a estar instalado (tanto por repositorio como localmente).

Como comentario al margen acabo de subir un bug al issue tracker de Ubuntu, así en un futuro los usuarios de Ubuntu lo pueden instalar de repositorio sin tener que pasar por la compilación.

https://bugs.launchpad.net/ubuntu/+bug/1572532

Con respecto a lo que te está pasando, el error que te está tirando ahora es un error del linker. Es decir, termina la compilación sin problemas, pero cuando intenta linkear contra las librerías que tenés instaladas se encuentra con un problema de versiones. Este problema puntual surge de que hay una transición entre versiones de Qt, y se está migrando todo de Qt4 a Qt5. Como estas dos versiones son incompatibles, ambas coexisten en muchas distribuciones hasta que todos los programas se terminen de portar a la versión más nueva (Qt5). Caneda ya está utilizando Qt5.

Para poder linkear todo correctamente, se debe linkear contra todo contra la misma versión. Cuando el compilador trata de linkear Qwt (la línea que dice "/usr/bin/ld: /usr/local/qwt-6.1.2/lib/libqwt.so: referencia sin definir al símbolo '_ZN13QSvgGeneratorC1Ev'"), lo está intentando linkear contra la versión vieja (la línea que dice "/usr/lib/x86_64-linux-gnu/libQtSvg.so.4: error adding symbols...") y aparece el error. El 4 al final es un indicativo (libQtSvg.so.4). Como el resto del programa se está linkeando contra Qt5, no puede proseguir. Para confirmar que está pasando esto, deberías ejecutar:

qmake -v

y si te tira que está utilizando la versión 4.X.X de Qt, encontramos efectivemente el problema. Para solucionarlo, no vas a poder desinstalar Qt4 ya que muy probablemente otros programas lo utilicen (y tengas que desinstalar medio sistema operativo). La alternativa es indicarle al compilador que tiene que utilizar Qt5 para compilar Qwt.

Si hasta acá se dan las cosas como te menciono antes, te propongo hacer lo siguiente:

- Eliminar la instalación local de Qwt y todos sus archivos ("/usr/local/qwt-6.1.2/"). Cuidado al borrar cosas del raíz, de no borrar cosas de más.
- Ejecutar en una consola `export QT_SELECT=5` para setear la variable de entorno que le indica a Qt utilizar Qt5 para compilar. Esta variable es local a la consola que tengas abierta, así que si la cerras y volvés a abrir, se "limpia" esa variable y tendrías que volver a ejecutar el comando anterior.
- Ejecutar nuevamente `qmake -v`. Esta vez te debería indicar alguna versión de Qt5.
- Recompilar Qwt, y volverlo a instalar. Esta vez debería instalarse (si todo sale bien) Qwt compilado y linkeado contra Qt5.
- Finalmente borrar el interior de la carpeta build de Caneda y recompilar. Como ahora Qwt estaría compilado contra Qt5, debería andar bien.

Igual que antes, espero no haberte mareado. Por favor, manteneme al tanto si podés solucionar el problema ya que en el camino realicé varias suposiciones.

**Comment by parejaobregon** [comment]
Agrego un comentario adicional que no tiene relación con el bug, para ahorrar dolores de cabeza.

Caneda utiliza como motor de simulación ngspice. Esto es configurable desde los settings y en realidad se puede utilizar cualquier motor que se prefiera. Si bien no es una dependencia fuerte ya que el programa teóricamente se podría utilizar para simplemente dibujar circuitos, me parece importante indicar al usuario si está faltando instalar dicho motor. En la versión de desarrollo (la rama development) se corrigen varios bugs y se incorpora un chequeo para avisar de este error.

Si al intentar simular, no se obtienen los resultados de la simulación, chequear de tener instalado el paquete ngspice. Agrego algunos links de referencia.

- http://ngspice.sourceforge.net/packages.html
- https://launchpad.net/ubuntu/+source/ngspice
- https://packages.debian.org/sid/ngspice

**Comment by victorchoke** [comment]
Hola tuve ya saltamos ese escoyo y era exactamente lo que preveías. Ahora me sucede este que es de las mismas condiciones,

[ 59%] Built target dialogs
Linking CXX executable caneda
/usr/bin/ld: dialogs/libdialogs.a(exportdialog.cpp.o): referencia sin definir al símbolo '_ZN13QSvgGenerator7setSizeERK5QSize'
/usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.4.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/caneda.dir/build.make:1044: recipe for target 'src/caneda' failed
make[2]: *** [src/caneda] Error 1
CMakeFiles/Makefile2:83: recipe for target 'src/CMakeFiles/caneda.dir/all' failed
make[1]: *** [src/CMakeFiles/caneda.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

En que parte figuran las variables de entorno? O como puedo acceder a ellas para modificarlas.

**Comment by parejaobregon** [comment]
Para listar las variables de entorno de la terminal actual, basta con ejecutar el comando `printenv` y para modificar alguna, `export nombre_de_variable=valor`.

El error que te está tirando es un error de linkeo, la diferencia es que ahora tiene problemas para linkear contra uno de los diálogos del código de Caneda. Según el mensaje de error, el linkeo tiene problemas con el diálogo exportdialog. Ese diálogo está en la carpeta `caneda_sources/src/dialogs/`. En particular, las instrucciones de linkeo contra libQt5Svg están en el archivo CMakeLists.txt dentro de esa carpeta, es decir el archivo `caneda_sources/src/dialogs/CMakeLists.txt`. Dentro de ese archivo hay una linea que dice:

`TARGET_LINK_LIBRARIES( dialogs
  Qt5::PrintSupport
  Qt5::Svg
  ${QWT_LIBRARIES}
)`

De esa sentencia, Qt5::Svg es un atajo de Qt que indica cómo linkear Qt5Svg. Lo que me llama la atención es que la configuración de mi máquina no es muy distinta de la tuya. Si no es mucha molestia, me gustaría saber qué paquetes referidos a Qt tienes instalados, para compararlos con los que tengo yo. Los mismos los puedes listar mediante el comando:

`aptitude search ~iqt`

Por otra parte, voy a instalar Ubuntu 15.04 en una máquina virtual para intentar realizar los mismos pasos que estás haciendo vos (yo en mi máquina uso Debian) y ver si puedo replicar tu problema.

**Comment by parejaobregon** [comment]
Ahí logré compilar e instalar Caneda en Ubuntu 15.04 (que es la versión que indicás en el reporte). Traté de minimizar los pasos que realicé para que todo fuera lo más parecido posible a tu sistema, y tratar de repetir el error, pero no tuve suerte. Te cuento los pasos que hice para ver si te pueden ayudar a resolver el problema:

- Hice una instalación desde cero en una máquina virtual (usé Virtualbox) con todos los pasos por default, sin cambiar nada.
- Para instalar las librerías o paquetes necesarios utilicé synaptic ya que es lo que entendí que estabas usando.
- Al principio no instalé nada, y a medida que me fue tirando distintos errores de compilación,  fui instalando los paquetes mínimos necesarios. Esto lo hice así, para no instalar nada de más y tener lo mínimo posible instalado. Al final del proceso, los siguientes paquetes fueron los que instalé (el último no hace falta para compilar, pero se utiliza luego para simular).
  - qt5-qmake
  - libqt5svg5-dev
  - qtbase5-dev
  - qttools5-dev
  - qttools5-dev-tools
  - ngspice
- Bajé las fuentes de qwt y Caneda, descomprimí ambos archivos fuentes.
- Ejecuté los siguientes pasos:
```
export QT_SELECT=5
cd qwt
qmake qwt.pro
make
sudo make install
cd ..
cd Caneda-master
mkdir build
cd build
cmake ..
make
sudo make install
```
Finalmente ejecuté Caneda con el siguiente comando:

`LD_LIBRARY_PATH=/usr/local/qwt-6.1.2/lib/ caneda`

Es necesario pasarle el parámetro LD_LIBRARY_PATH ya que instalamos qwt en una ubicación no estándar del sistema. Si se hubiera instalado en otro lugar no haría falta, pero quise dejar todo por default. En este punto anduvo todo y obtuve la captura que muestro a continuación:

![canedaatubuntu](https://cloud.githubusercontent.com/assets/12896960/14763193/b5433e78-0964-11e6-9317-b7ba4589efbc.png)

**Comment by victorchoke** [comment]
Perfecto, con el procedimiento que me indicaste lo pude hacer lo mas bien, estoy haciendo todo por consola, mediante apt y aptitude, igual mente lo hice en otra maquina con la misma versión de S.O el problema en la otra maquina era que tenia dependencias rotas.

Muchas gracias!!!!
![captura de pantalla](https://cloud.githubusercontent.com/assets/18563442/14771009/c935b208-0a54-11e6-8965-f3d9930afe8f.png)

**Comment by parejaobregon** [comment]
¡Excelente! No te olvides de agregar una tierra al circuito :)

Normalmente recomendaría usar master, pero por las dudas te comento que en este momento la versión de la rama develop incluye varias correcciones a bugs algo molestos (incluídos algunos crashes) y algunos mensajes de aviso, como por ejemplo si te falta incluir la tierra.

https://github.com/Caneda/Caneda/tree/develop

También estoy creando la documentación en:

http://caneda.readthedocs.org/

De a poco la iré completando. Como recursos adicionales en el menú "Help" hay una entrada "Example Circuits..." que te permite bajar algunos circuitos de ejemplo. En "Application Settings -> Libraries -> Get new libraries" podés conseguir componentes comerciales (como un diodo 2n2222). Tengo varios miles de componentes comerciales armados que iré agregando a medida que tenga tiempo, si necesitás alguno particular, avisame y voy agregando primero aquellos que tengan más demanda.

Si te surge alguna otra cosa o encontrás algo a mejorar, no dudes en abrir un ticket nuevo... siempre es bienvenido el feedback.
