### ISSUE TITLE
What is the "Miscellaneous => Model" thing for?

### ISSUE THREAD

**Issue by morciej** [Caneda/Caneda#10]
Hi there,

First of all, thank you that we radio amateurs and hams don't have to buy PSPICE to have fun with some ccts.

I am trying out **"Caneda"** because I am trying to build a detector for 144MHz SWR meter. I thought it would be easier to simulate the Shottky diode, rather than figure out the output voltage relationship, capacitance effects etc. by hand.

Modifying the diode model worked after a fashion, but I am afraid that the model parameters I left alone (since they cannot be removed; it's a regular diode after all) will change the result. That's why I would prefer to use a complete SPICE model of this Shottky that I have from the manufacturer.

There is **"something looking useful, but APPARENTLY undocumented"** called "Miscellaneous" => "Model" in the Components Browser. Its instance gets labeled "CUSTOM_MODEL" -- so far so good!

But try as I might, I cannot get it to work successfully. I change model type from R to D. I change model=SHOTTKY and label=1N6263. I put in all the SPICE parameters. I give the diode in circuit the model "1N6263" instead of "D". Then I try to simulate.

Unfortunately, the system finds some "extraneous character(s)" before the word "model" (looks like a % sign but what do I know?) and refuses to run the simulation.

Needless to say, I am not familiar at all with SPICE simulations, as I never had to go so deep into sim software to actually demand specific model parameters. And it was years ago under Windows.

Is this "CUSTOM_MODEL" business documented somewhere, so that we can use a proper custom model for a Shottky?

FWIW here's the SPICE file from which I extracted the parameters:

```
*******************************************************************
* SMALL SIGNAL SCHOTTKY DIODE 60V,70V,80V & 100V
*******************************************************************
*******************************************************************
* Model name       : 1N6263
* Description      : Small signal Schottky diode
* Package type     : DO35
*******************************************************************
.MODEL 1N6263 D IS=3.8736E-9 N=1.0099 RS=31.514 IKF=18.247 CJO=1.7738E-12
+ M=.1955 VJ=.3905 ISR=6.2866E-9 NR=3.9204 FC=0.5 TT=0 XTI=2
```

The netlist:

```
* Spice automatic export. Generated by Caneda.

* Spice netlist.
DD1 1 2 1N6263 area=1.0 m=1.0 pj=1.0 ic=0 temp=26.5 dtemp=1.0 
%model{SHOTTKY D ( .MODEL 1N6263 D IS=3.8736E-9 N=1.0099 RS=31.514 IKF=18.247 CJO=1.7738E-12
M=.1955 VJ=.3905 ISR=6.2866E-9 NR=3.9204 FC=0.5 TT=0 XTI=2 )}
TT1 3 1 0 0 Z0=50 TD=66p IC=0,0,0,0
RR2 2 0 2k m=1.0 scale=1.0 temp=26.5 dtemp=1.0 tc1=0.0 tc2=0.0 noisy=0
CC1 2 0 1e-9 C m=1.0 scale=1.0 temp=26.5 dtemp=1.0 tc1=0.0 tc2=0.0 ic=0 
VV1 3 0 DC 0.5 AC 0.5 0 SIN( 0 0.5 146e6 0.0 0.0 )
RR1 1 0 47 m=1.0 scale=1.0 temp=26.5 dtemp=1.0 tc1=0.0 tc2=0.0 noisy=0

CC2 1 2 2e-12 C m=1.0 scale=1.0 temp=26.5 dtemp=1.0 tc1=0.0 tc2=0.0 ic=0 

* Device models.
.model D D
.model C C

* Spice directives.
.tran 10e-12 1300e-9 0 
```
And last but not least here's the attempted simulation log

```
Warning: Unusual leading characters like '%' or others out of '= [] ? () & % $"!:,;\f'
    in netlist or included files, will be replaced with '*'.
    Check line no 5:  %model{shottky d ( .model 1n6263 d is=3.8736e-9 n=1.0099 rs=31.514 ikf=18.247 cjo=1.7738e-12

warning, can't find model '1n6263' from line
    dd1 1 2 1n6263 area=1.0 m=1.0 pj=1.0 ic=0 temp=26.5 dtemp=1.0
    Simulation interrupted due to error!

Error: circuit not parsed.
Note: no resource usage information for 'time',
	or no active circuit available

No compatibility mode selected!


Circuit: * spice automatic export. generated by caneda.

Error on line 4 :
  dd1 1 2 1n6263 area=1.0 m=1.0 pj=1.0 ic=0 temp=26.5 dtemp=1.0
could not find a valid modelname


Total elapsed time (seconds) = 0.004 

Total DRAM available = 7882.398 MB.
DRAM currently available =  639.461 MB.
Maximum ngspice program size =   19.883 MB.
Current ngspice program size =   12.020 MB.

Shared ngspice pages =   10.398 MB.
Text (code) pages =    5.316 MB.
Stack = 0 bytes.
Library pages =    1.938 MB.
```
This is the schematic:

![Schematic](https://github.com/user-attachments/assets/5b019226-2bc5-4e1a-9749-dccb30c17f6d)

Thanks, I appreciate for someone to look into it and telling me the obvious I am sure.

Matthew

**Comment by parejaobregon** [comment]
By the way, in reference to the above, if you consider any of your circuits is worth adding as an example to the **Examples** repository, please let me know and we can add a new **ham_radio** folder or something similar. Then you can share what you are working on with the community.

Take into account that there's also the possibility to create a symbol with ports for any schematic, and then you can reuse that in other, more complex designs, going one level up in the hierarchy (we can even create a ham library with many schematic/symbols instead of just examples).

Just food for thought.

**Comment by morciej** [comment]
Right now I am not even able to simulate a simple 90° hybrid coupler. It just doesn't do what these things are supposed to do, and I have no idea why. It's four pieces of transmission line joined in a square. What could be simpler? I get no isolation at all. If this doesn't work, I have no hope of simulating the circuit that's failing me in real life. I'll keep digging, but this is taking time away from actually doing my hobby.
