### ISSUE TITLE
Graph colors - feature request

### ISSUE THREAD

**Issue by morciej** [Caneda/Caneda#11]
I have a feature request.

The **colors of graphs** are making it impossible to correctly set any specific color for **background**. Yellow is hard to see on bright backgrounds, dark ones are not visible on dark. I know that young eyes can see basically any combination crystal clear, but at 60 I am not in that cohort. Most ham radio guys I know are old, and we are the ones who need this software.

Please select a different set of colors according to where in the color space is the simulation background. It should be simple to move the whole palette proportionately in brightness away from the selected background color. You can even do it in just two selections: bright or dark. Just don't mix them.

Such settings are better off in an explicit initialization file, rather than compiled in. Quite a few of us have issues with color perception, and we need to tweak these things in any case.

Thanks,

Matthew

**Comment by parejaobregon** [comment]
Hey Matt,

Sorry for the delay in the response, bear in mind I'm working on this on my
spare time.

Thanks for your inputs, and glad you could solve the other issue.

Did you try changing the background on the general settings? If I remember
correctly, there was an option for that. If not, please let me know and I
can revisit the issue.

Thanks again!!!

**Comment by morciej** [comment]
The closest simulation background I could tolerate was medium grey, making everything equally muddy and difficult to see. Since the smallest change in the schematic reassigns the colors, I can't even ignore the worst choices that randomly obscure my work.

This color confusion is based on the **original PC idea** that we use **light grey on black** as default for writing, with white or later, **color highlights**, in an extremely limited palette of 16 colors. With VGA, there are better choices. We have to set aside the idea that bright colors are suitable for graphing or writing, unless we change the whole premise by switching to a dark theme (which has its own set of issues.)

These are basic ergonomic UI choices.

**Comment by parejaobregon** [comment]
I see. So it's not a matter of the actual colors, but rather the contrast between the current background and some of the selected colors in the palette that have a brightness near that background.

I'll try to see if I come up with a solution. We need to keep the plot colors automatic since we don't know beforehand how many plots a sim will have. But, we can nevertheless pick some range according to the background selection.

As a side note, take into account this software is not intended only for ham radio, but rather for circuit simulations in general. So strictly speaking the target audience you mention is not the original intent (although surely it can be used for that scenario). These kind of simulations include a much broader public (myself included) that work with electronics. In any case, your point taken, I'll try to fix the colors.

Thanks for your inputs.

**Comment by parejaobregon** [comment]
@morciej I've been experimenting with this a little bit and I noticed that the colors used are relatively similar to those used on other software. Nevertheless, I also noticed the width of the pen used was very thin in comparison, which may have contributed to the cause. I do indeed agree the plots are hard to see (I have not noticed that before, it may depend on the display resolution or other factors).

Meanwhile, I started experimenting changing the pen widths and it looks like the situation improves a lot, some screenshots below.

**Before any change:**
![Screenshot_20240926_before](https://github.com/user-attachments/assets/654bbb5a-a268-471c-aaec-4bf2d5971e55)

![Screenshot_20240926_before_white](https://github.com/user-attachments/assets/45c8ee50-7af2-44c4-8cee-de6d3065fd53)

**After changing the pen to a fixed width = 2:**
![Screenshot_20240926_after](https://github.com/user-attachments/assets/20f3a7e4-4bcb-4c83-8ef7-5abc1eaadd25)

![Screenshot_20240926_after_white](https://github.com/user-attachments/assets/9c45840e-8311-4060-942b-120ff948c7ec)

@morciej do you think this partial solution would work for you? We might change the default for the simulation background to black as well.

I might work in the future on adding the possibility to select individual colors for each plot, but that will need more time/work so I cannot make any promises on a timeframe in that regard.

**Comment by morciej** [comment]
That's a bit better. I'd prefer if you could make two different palettes for graph lines, one for bright backgrounds, one for dark. Yellow will really never be readable on bright backgrounds etc.

**Comment by parejaobregon** [comment]
Agreed. At least for the time being we have something. I need to devise a way to make this dynamically since we don't know the number of plots beforehand.

I'll keep the issue open.

**Comment by parejaobregon** [comment]
I made a couple of changes to the current scheme to fix this. The currently default colours should still be the same, but now you have the possibility to set any range of colours you need in the HSV space (color hue, saturation, value).

The new settings were moved (alongside the simulation background) into the **Simulations** tab within the **Settings Dialog**.

![imagen](https://github.com/user-attachments/assets/92aad6d3-0f7e-43fe-8df9-e5829e177b14)

This needs to be documented a little bit, but for the time being, the rationale is this:

- **Background color** works a before
- **Line color start** is the target color range initial color (initial color selected for any given number of plots)
- **Line color end** is the target color range end color (last color in the selected range before starting over)
- **Line color steps** are the number of colors automatically selected **in between** the start and end colors (doesn't include the start and end).
- **Line width** is the width of the pen used for the plots

The color selection will move linearily in the HSV space, which behaves more naturally than RGB, using N steps to calculate the colors in between. In this way, one can select any saturation, brightness or range of colors based on the background and personal preferences. If enough plots are present, once the end color has been reached, the selection starts over from the initial color.

Some examples:
- If you select the same start and end colors, no matter the steps, all plots will have the same color
- If you select two different colors with many steps in between, the color difference between curves will be small and subsequent curves will look very similar but the colors will never repeat
- If you select two different colors with a small step value, the color difference between curves will be bigger, but the end color will be reached sooner and the colors will start over
- For any simulation, if you select the steps equal to the number of plots (minus 2) the colors will never repeat
- The increments may go up or down, depending on which color you select as the first and second ones.

Depending on the needs, different settings may be used. A sane recommendation would be to select a range that leaves out any color you don't want and use a relatively small step increment (say 4-8). This way the colors will not repeat and still they will have room for the colors to be pretty different one from each other.

**Comment by parejaobregon** [comment]
@morciej I believe the fix above should suit your needs. I you feel this needs further improvement, please let me know.

**Comment by parejaobregon** [comment]
Oh, and sorry but for the time being, the settings are read during the first load of the view, so you will need to restart the application after applying a new color to experiment with this :(

This is in my todo list.

**Comment by morciej** [comment]
I'll get the development version and recompile but it looks very good as an idea.
