### ISSUE TITLE
Problemas en la ejecucion

### ISSUE THREAD

**Issue by victorchoke** [Caneda/Caneda#2]
Hola ahora estoy instalando sobre debian 8
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

Mi consulta es la siguiente, según entiendo. Cmake hace uso de qmake para la compilacion y instalación de caneda, pero por alguna razon no reconoce la versión que instale manualmente de qt5 en mi computadora (la versión de qt5 de debian por defecto es muy engorrosa ir instalando las librerias de desarrollo para ir configurando una por una). El tema es que no se como pasarle como parámetro o variable de entorno la nueva ubicación del qt5 o del qmake al cmake para que no use el por defecto instalado en mi sistema (y lo mismo para la libreria qwt). Devolviéndome errores como el siguiente:

CMake Error at CMakeLists.txt:14 (FIND_PACKAGE):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets"
  (requested version 5.3.2) with any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/ping/develop/Caneda/build/CMakeFiles/CMakeOutput.log".

Paso las variables a CMAKE_PREFIX_PATH y puedo seguir instalando lo mas bien, el tema es que cuando ejecuto el programa sigue buscando en las librerias locales en ves de las manuales con las que pase como variable de entorno. Dandome este error:

caneda
caneda: /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5: no version information available (required by caneda)
caneda: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5: no version information available (required by caneda)
caneda: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by caneda)
caneda: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by caneda)
caneda: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by caneda)
caneda: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by caneda)
caneda: symbol lookup error: caneda: undefined symbol: _ZTI17QwtPlotSeriesItem

El tema es que se nota que caneda no accede a mi instalación manual de qt5 para ejecutarse ni a la de qwt

Como podria solucionarlo?

**Comment by caputchinefrobles** [comment]
Please, post your issue in English, there's a bigger change people might help you. 

In this case, it seems like you're missing Qt5Widgets module (libqt5widgets5 in debian 9). Make sure you've installed all dependency libs before compilation.

**Comment by parejaobregon** [comment]
Hola Victor.

No termino de entender a qué te refieres cuando pones "...la versión de qt5 de debian por defecto es muy engorrosa ir instalando las librerias de desarrollo para ir configurando una por una...". Mi consejo es utilizar las versiones disponibles en la distribución. De hecho, son las mismas que uso yo para desarrollar.

En http://docs.caneda.org/ se está reuniendo documentación del programa, con una guía paso a paso para realizar la instalación y compilación, además de tutoriales y otros recursos. Si utilizas Debian stable o testing, puedes instalar Caneda directamente desde los repositorios. Si prefieres de todas maneras hacer una compilación manual, puedes utilizar como guía http://docs.caneda.org/en/latest/compilation.html donde hay puntualmente una guía específica para Debian 8, que es el que estás utilizando. Básicamente para instalar todas las dependencias de la compilación (y no tener que instalar una por una), debes ejecutar:

aptitude install git cmake g++ qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools
