### ISSUE TITLE
feature request - two port voltmeter

### ISSUE THREAD

**Issue by akdor1154** [Caneda/Caneda#3]
Would be great to be able to create a two-port voltmeter to measure the difference between two nodes.

I'm not a spice expert so I got confused trying to do this with spice directives and eventually gave up..

**Comment by akdor1154** [comment]
Currently working around this with a voltage-dependant voltage source.

**Comment by parejaobregon** [comment]
Fixed in latest commit.

Added two port (differential) voltmeter based on a voltage controlled voltage source. As a nice side effect, the voltmeter can have a gain factor to adjust the output measurements for easier comparisons.
