### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Tynach** [Caneda/Caneda#6]
I don't see any activity by @parejaobregon here since 2017. This is unfortunate, as KiCad gives me tons of issues and Caneda seems to be the best open source program for setting up simple circuits and simulations (as a function of both ease of use and functionality).

I suppose I could give Electric another try, but I had issues with its simulation capabilities in the past.

Or, is the developer instead helping out with bringing [KTechLab] into the Qt5 era?

[KTechLab]: https://github.com/ktechlab/ktechlab

**Comment by chgans** [comment]
Maybe you can contribute or fork and maintain? Have you tried Qucs? There's as well a Qucs-S friendly fork that add support for spice.
See:
https://github.com/Qucs/qucs
https://ra3xdh.github.io/

**Comment by parejaobregon** [comment]
Hi there,

The project is not dead at all. For the foreseeable future I plan to keep working on it and maintain it. Nonetheless, for personal reasons I've been lately not able to work on it as much as I'd like. I've got lots of improvements locally but I don't feel comfortable committing them until further testing. Again, you may not see much movement, but I'll keep things working and eventually there will be some movement back.

Have you encountered any issues that affect you as a user that may need some fix? If so, please let me know opening new tickets, and I'll work on then as soon as possible (at least sooner that the improvements mentioned above).

Thanks.

Regards,
Pablo
